name: Solar System Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}} 
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}

jobs:
    
    unit-testing:
        name: unit testing
        strategy:
            matrix:
              Node_V: [18,19,20]
              os: [ubuntu-latest,macos-latest]
              exclude:
                - Node_V: 18
                  os: macos-latest

        runs-on: ${{matrix.os}}
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup-nodejs
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.Node_V}}
            - name: install depen..
              run : npm install
            - name: unit-test
              run : |
                npm test
                ls
            - name: upload
              uses: actions/upload-artifact@v4
              with:
                name: test-result ${{matrix.os}},${{matrix.Node_V}}
                path: ./test-results.xml
    code-coverage:
        name: code coverage
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup-nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: install depen..
              run : npm install
            - name: unit-test
              continue-on-error: true
              run : |
                npm run coverage
                
            - name: upload
              uses: actions/upload-artifact@v4
              with:
                name: coverage-result
                path: ./coverage
            